services:
  fastzero_database:
    image: postgres:17
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  fastzero_app:
    image: fastzero_app
    build: .
    entrypoint: ./entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - fastzero_database
    environment:
      DATABASE_URL: postgresql+asyncpg://app_user:app_password@fastzero_database:5432/app_db

volumes:
  pgdata: 