name: pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL:${{ secrets.DATABASE_URL }}
      SECRET_KEY:${{ secrets.SECRET_KEY }}
      ALGORITHM:${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES:${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}

    steps:
    #copia os arquivos do reposit√≥rio
    - uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install Poetry
      #run: |
      #  curl -sSL https://install.python-poetry.org | python3 -
      #  echo "::add-path::${HOME}/.local/bin"
      run: |
        pipx ensurepath
        pipx install poetry

    - name: Install dependencies
      run: |
        poetry install

    - name: Run tests
      run: |
        poetry run task test